export const csgoWeapons = [
    "CZ75-Auto",
    "Desert Eagle",
    "Dual Berettas",
    "Five-SeveN",
    "Glock-18",
    "P2000",
    "P250",
    "R8 Revolver",
    "Tec-9",
    "USP-S",
    "AK-47",
    "AUG",
    "AWP",
    "FAMAS",
    "G3SG1",
    "Galil AR",
    "M4A1-S",
    "M4A4",
    "SCAR-20",
    "SG 553",
    "SSG 08",
    "MAC-10",
    "MP5-SD",
    "MP7",
    "MP9",
    "PP-Bizon",
    "P90",
    "UMP-45",
    "MAG-7",
    "Nova",
    "Sawed-Off",
    "XM1014",
    "M249",
    "Negev",
    "Nomad Knife",
    "Skeleton Knife",
    "Survival Knife",
    "Paracord Knife",
    "Classic Knife",
    "Bayonet",
    "Bowie Knife",
    "Butterfly Knife",
    "Falchion Knife",
    "Flip Knife",
    "Gut Knife",
    "Huntsman Knife",
    "Karambit",
    "M9 Bayonet",
    "Navaja Knife",
    "Shadow Daggers",
    "Stiletto Knife",
    "Talon Knife",
    "Ursus Knife"
  ];
  export const csgoRarities = [
    'Base Grade',
    'Consumer',
    'Industrial',
    'Mil-Spec Grade',
    'Restricted',
    'Classified',
    'Covert',
    'Rare Special',
    'Contraband',
    //Agents
    'Master',
    'Superior',
    'Distinguished',
    'Exceptional',
    //Stickers
    'High Grade',
    'Remarkable',
    'Exotic',
    'Extraordinary',
    'Contraband',
  ];
  export const csgoFloats = [
    'Factory New',
    'Minimal Wear',
    'Field-Tested',
    'Well-Worn',
    'Battle-Scarred'
  ];
  